#!/usr/bin/env bun
/**
 * Reads the Vite build output from web-client/dist/web/ and produces
 * crates/lukan-web/src/embedded_ui.rs which inlines all HTML/CSS/JS
 * so the compiled binary can serve them without filesystem access.
 */
import { readFileSync, readdirSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "..");
const DIST_DIR = join(ROOT, "web-client/dist/web");
const OUT_FILE = join(ROOT, "crates/lukan-web/src/embedded_ui.rs");

// Read index.html
let html = readFileSync(join(DIST_DIR, "index.html"), "utf-8");

// Read all assets and inline them
const assetsDir = join(DIST_DIR, "assets");
const assets = readdirSync(assetsDir);

for (const file of assets) {
  const content = readFileSync(join(assetsDir, file), "utf-8");

  if (file.endsWith(".css")) {
    // Replace <link ...href="/assets/FILENAME"...> with inline <style>
    const linkRegex = new RegExp(
      `<link[^>]*href="/assets/${file.replace(/\./g, "\\.")}"[^>]*>`,
      "g",
    );
    html = html.replace(linkRegex, () => `<style>${content}</style>`);
  } else if (file.endsWith(".js")) {
    // Replace <script ...src="/assets/FILENAME"...></script> with inline <script>
    const scriptRegex = new RegExp(
      `<script[^>]*src="/assets/${file.replace(/\./g, "\\.")}"[^>]*></script>`,
      "g",
    );
    html = html.replace(scriptRegex, () => `<script type="module">${content}</script>`);
  }
}

// Verify all /assets/ references were inlined
if (html.includes("/assets/")) {
  console.error("WARNING: Some asset references were not inlined!");
  const remaining = html.match(/\/assets\/[^"'\s]+/g);
  if (remaining) remaining.forEach((r: string) => console.error("  -", r));
}

// Escape for Rust raw string (## delimiters)
// We need to escape any occurrences of "##" in the HTML
const escaped = html.replace(/##/g, "#​#"); // zero-width space between — shouldn't occur in practice

const output = `// Auto-generated by scripts/embed-web.ts — do not edit manually
pub const EMBEDDED_HTML: &str = r##"${html}"##;
`;

await Bun.write(OUT_FILE, output);

// Quick sanity check
const hasStyle = output.includes("<style>");
const hasScript = output.includes('<script type="module">');
console.log(
  `✓ Embedded web UI written to crates/lukan-web/src/embedded_ui.rs (${(output.length / 1024).toFixed(1)}kb)`,
);
console.log(`  CSS inlined: ${hasStyle}, JS inlined: ${hasScript}`);
